[build]
  command = """
    sudo apt-get update -qq && \
    sudo apt-get install -y postgresql-client libpq-dev && \
    bundle install && \
    bundle exec rake assets:precompile && \
    bundle exec rake db:migrate
  """
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  RUBY_VERSION = "2.7.8"

[[plugins]]
  package = "@netlify/plugin-nextjs" 