[build]
  command = """
    nix-shell -p postgresql pkgconfig --run "bundle install && bundle exec rake assets:precompile"
  """
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  RUBY_VERSION = "2.7.8"
  # PostgreSQL build configuration
  PGUSER = "dummy"
  PGPASSWORD = "dummy"
  PGDATABASE = "dummy"
  PGHOST = "dummy"
  DATABASE_URL = "postgresql://dummy:dummy@dummy/dummy"

[[plugins]]
  package = "@netlify/plugin-nextjs" 